# Generated by Django 3.0.5 on 2020-12-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_prob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
