# Generated by Django 3.0.5 on 2020-12-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_prob', '0002_auto_20201220_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(),
        ),
    ]
